modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/buddiman/AllTheMachines/issues"

[[mods]]
    modId="allthemachines"
    version="alpha"
    displayName="All the Machines"
    displayURL="https://github.com/buddiman/AllTheMachines"
    authors="buddiman"
    credits="buddiman"
    description='''ALLES WAS MAN WILL KANN DES DING'''


[[dependencies.allthemachines]]
    modId="minecraft"
    mandatory=true
    versionRange="1.14"
    side="BOTH"
[[dependencies.allthemachines]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    side="BOTH"
